"""phase 4: per-user quota override and estimated job cost

Revision ID: 07861866bba4
Revises: e05f1aec0495
Create Date: 2026-08-30 21:30:05.694788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07861866bba4'
down_revision = 'e05f1aec0495'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estimated_cost_usd', sa.Float(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quota_jobs_per_day', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('quota_jobs_per_day')

    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.drop_column('estimated_cost_usd')

    # ### end Alembic commands ###
