"""per-step timings, actual translator, for fallback tracking

Revision ID: 5645cfa42939
Revises: 07861866bba4
Create Date: 2026-08-31 01:30:20.677273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5645cfa42939'
down_revision = '07861866bba4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('translator_actual', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('extract_sec', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('transcribe_sec', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('translate_sec', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('tts_sec', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('compose_sec', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.drop_column('compose_sec')
        batch_op.drop_column('tts_sec')
        batch_op.drop_column('translate_sec')
        batch_op.drop_column('transcribe_sec')
        batch_op.drop_column('extract_sec')
        batch_op.drop_column('translator_actual')

    # ### end Alembic commands ###
