"""transcript segments per job

Bang giu transcript song ngu kem moc thoi gian. Truoc day noi dung nay chi
nam trong file .srt tren Volume nen khong truy van duoc, va mat han khi
nguoi dung chon subtitle_mode "vi" hoac "none".

Revision ID: ac36db2cb97b
Revises: 1328f180f28a
Create Date: 2026-08-31 17:07:36.361434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac36db2cb97b'
down_revision = '1328f180f28a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transcript_segment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('idx', sa.Integer(), nullable=False),
    sa.Column('start_sec', sa.Float(), nullable=False),
    sa.Column('end_sec', sa.Float(), nullable=False),
    sa.Column('text_en', sa.Text(), server_default='', nullable=False),
    sa.Column('text_vi', sa.Text(), server_default='', nullable=False),
    sa.Column('edited', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'idx', name='uq_transcript_segment_job_idx')
    )
    with op.batch_alter_table('transcript_segment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transcript_segment_job_id'), ['job_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transcript_segment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transcript_segment_job_id'))

    op.drop_table('transcript_segment')
    # ### end Alembic commands ###
